/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.weldbit.scout;

import java.io.IOException;
import java.io.InputStream;

import com.weldbit.scout.storage.model.TableLedger;
import com.weldbit.scout.storage.model.TableStructure;
import com.weldbit.scout.storage.service.DataManagement;
import com.weldbit.scout.storage.service.DataStorage;

import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.constructor.Constructor;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        App app = new App();
        // System.out.println(new App().getGreeting());
        // HttpClient client = HttpClient.newHttpClient();
        // HttpRequest request =
        // HttpRequest.newBuilder().uri(URI.create("http://www.google.com/")).build();

        // String htmldoc;
        // htmldoc = client.sendAsync(request,
        // BodyHandlers.ofString()).thenApply(HttpResponse::body).join();
        // // System.out.println(htmldoc);
        // Document doc = Jsoup.parse(htmldoc);

        // String text = doc.body().text(); // "An example link"

        // System.out.println(doc.title());

        // List squares = new ArrayList();
        // Flowable.range(1, 64) // 1
        // .observeOn(Schedulers.computation()) // 2
        // .map(v -> v * v) // 3
        // .blockingSubscribe(squares::add); // 4

        // for (Object object : squares) {
        // System.out.println(object);
        // }

        // Stack<Integer> mystack = new Stack<Integer>();
        // mystack.push(1);
        // System.out.println(mystack.getTop());

        // DataAccessBase tableLedger = new TableLedgerDAO();
        // tableLedger.createTable();
        // System.out.println(tableLedger.readTable());
        // System.out.println("Stream below");
        // tableLedger.readTable();

        // TableLedger tLedger = new TableLedger();
        // tLedger.setTablename("what filename");

        // try (DataStorage<TableLedger> tblLedger = new DataStorage<>(tLedger,
        // DataStorage.ACCESS_TYPE.WRITE)) {
        // tblLedger.insert();
        // } catch (IOException e) {
        // e.printStackTrace();
        // }

        DataManagement dataManagement = new DataManagement("datafile_meta/post.yml");
        // Yaml yaml = new Yaml(new Constructor(TableStructure.class));
        // InputStream inputStream =
        // app.getClass().getClassLoader().getResourceAsStream("datafile_meta/post.yml");

        // TableStructure tablestructure = yaml.load(inputStream);
        // System.out.println(tablestructure.toString());

        // try (DataStorage<TableLedger> tblLedger = new DataStorage<>(tLedger,
        // DataStorage.ACCESS_TYPE.WRITE)) {
        // tblLedger.insert();
        // } catch (IOException e) {
        // e.printStackTrace();
        // }
    }
}
